# Files
db_file                   "/home/mr/.config/mpd/database"
state_file                "/home/mr/.config/mpd/state"
pid_file                  "/home/mr/.config/mpd/pid"
sticker_file              "/home/mr/.config/mpd/sticker.sql"

# Directories  
music_directory           "/pool/Music/"
playlist_directory        "/pool/Music/Playlists"

# Network
bind_to_address           "localhost"
bind_to_address           "/home/mr/.config/mpd/socket"
port                      "6600"

# General settings
auto_update               "yes"
auto_update_depth         "2"
#max_output_buffer_size    "16384"
restore_paused            "yes"

# Audio
audio_output {
    type                    "pipewire"
    name                    "PipeWire Output"
    format                  "48000:16:2"
}

audio_output {
    type                    "fifo"
    name                    "Visualizer feed"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
