cursor                  #952eff
cursor_text_color       #7f4eb1

foreground              #952eff
background              #000001
selection_foreground    #7f4eb1
selection_background    #030307
url_color               #3e1880

color0   #000001
color8   #030307

color1   #080890
color9   #0c0c2b

color2   #4a0e8a
color10  #28153c

color3   #661a7e
color11  #3c2044

color4   #3e1880
color12  #32234c

color5   #112e8f
color13  #202d57

color6   #1a397e
color14  #24304c

color7   #952eff
color15  #7f4eb1
