# Hellpaper Hellwal template config
[Theme]
bg = 4, 14, 19, 255
idle = 39, 42, 64, 255
hover = 255, 255, 255, 255
border = 218, 236, 243, 255
ripple = 121, 133, 130, 255
text = 211, 202, 166, 255

[Settings]
base_thumb_size = 120
base_padding = 10
anim_speed = 20.0
particle_count = 100
max_fps = 200

[Effects]
# Valid effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = blur
keypress_effect = none
exit_effect = glitch
