# Hellpaper Hellwal template config
[Theme]
bg = 9, 4, 14, 255
idle = 64, 64, 112, 255
hover = 255, 255, 255, 255
border = 255, 255, 255, 255
ripple = 223, 187, 170, 255
text = 255, 255, 255, 255

[Settings]
base_thumb_size = 120
base_padding = 10
anim_speed = 20.0
particle_count = 100
max_fps = 200

[Effects]
# Valid effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = blur
keypress_effect = none
exit_effect = glitch
