$background = rgb(09040e)
$foreground = rgb(ffffff)

$color0 = rgb(09040e)
$color1 = rgb(404070)
$color2 = rgb(7e77ac)
$color3 = rgb(d9bb2b)
$color4 = rgb(dfbbaa)
$color5 = rgb(efdd72)
$color6 = rgb(d7d8ef)
$color7 = rgb(ffffff)
$color8 = rgb(28143c)
$color9 = rgb(50508c)
$color10 = rgb(9d94d7)
$color11 = rgb(ffe935)
$color12 = rgb(ffe9d4)
$color13 = rgb(ffff8e)
$color14 = rgb(ffffff)
$color15 = rgb(ffffff)
