cursor                  #ffffff
cursor_text_color       #ffffff

foreground              #ffffff
background              #09040e
selection_foreground    #ffffff
selection_background    #28143c
url_color               #dfbbaa

color0   #09040e
color8   #28143c

color1   #404070
color9   #50508c

color2   #7e77ac
color10  #9d94d7

color3   #d9bb2b
color11  #ffe935

color4   #dfbbaa
color12  #ffe9d4

color5   #efdd72
color13  #ffff8e

color6   #d7d8ef
color14  #ffffff

color7   #ffffff
color15  #ffffff
