cursor                  #daecf3
cursor_text_color       #ffffff

foreground              #daecf3
background              #040e13
selection_foreground    #ffffff
selection_background    #143c50
url_color               #798582

color0   #040e13
color8   #143c50

color1   #272a40
color9   #303450

color2   #52626f
color10  #667a8a

color3   #707070
color11  #8c8c8c

color4   #798582
color12  #97a6a2

color5   #828886
color13  #a2aaa7

color6   #a9a285
color14  #d3caa6

color7   #daecf3
color15  #ffffff
