# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#09040e\033\\"
printf "\033]4;1;#404070\033\\"
printf "\033]4;2;#7e77ac\033\\"
printf "\033]4;3;#d9bb2b\033\\"
printf "\033]4;4;#dfbbaa\033\\"
printf "\033]4;5;#efdd72\033\\"
printf "\033]4;6;#d7d8ef\033\\"
printf "\033]4;7;#ffffff\033\\"
printf "\033]4;8;#28143c\033\\"
printf "\033]4;9;#50508c\033\\"
printf "\033]4;10;#9d94d7\033\\"
printf "\033]4;11;#ffe935\033\\"
printf "\033]4;12;#ffe9d4\033\\"
printf "\033]4;13;#ffff8e\033\\"
printf "\033]4;14;#ffffff\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#09040e\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
