# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#040e13\033\\"
printf "\033]4;1;#272a40\033\\"
printf "\033]4;2;#52626f\033\\"
printf "\033]4;3;#707070\033\\"
printf "\033]4;4;#798582\033\\"
printf "\033]4;5;#828886\033\\"
printf "\033]4;6;#a9a285\033\\"
printf "\033]4;7;#daecf3\033\\"
printf "\033]4;8;#143c50\033\\"
printf "\033]4;9;#303450\033\\"
printf "\033]4;10;#667a8a\033\\"
printf "\033]4;11;#8c8c8c\033\\"
printf "\033]4;12;#97a6a2\033\\"
printf "\033]4;13;#a2aaa7\033\\"
printf "\033]4;14;#d3caa6\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#040e13\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
