# Generated by hellwal

wallpaper='/data/appdata/motoko/wallpapers/Edge Runner/03. Edge Runner.jpg'

background='09040e'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='09040e'
color1='404070'
color2='7e77ac'
color3='d9bb2b'
color4='dfbbaa'
color5='efdd72'
color6='d7d8ef'
color7='ffffff'
color8='28143c'
color9='50508c'
color10='9d94d7'
color11='ffe935'
color12='ffe9d4'
color13='ffff8e'
color14='ffffff'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
