# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#000001\033\\"
printf "\033]4;1;#080890\033\\"
printf "\033]4;2;#4a0e8a\033\\"
printf "\033]4;3;#661a7e\033\\"
printf "\033]4;4;#3e1880\033\\"
printf "\033]4;5;#112e8f\033\\"
printf "\033]4;6;#1a397e\033\\"
printf "\033]4;7;#952eff\033\\"
printf "\033]4;8;#030307\033\\"
printf "\033]4;9;#0c0c2b\033\\"
printf "\033]4;10;#28153c\033\\"
printf "\033]4;11;#3c2044\033\\"
printf "\033]4;12;#32234c\033\\"
printf "\033]4;13;#202d57\033\\"
printf "\033]4;14;#24304c\033\\"
printf "\033]4;15;#7f4eb1\033\\"

# Background
printf "\033]11;#000001\033\\";

# Foreground
printf "\033]10;#7f4eb1\033\\";

# Cursor
printf "\033]12;#7f4eb1\033\\";

# Border
printf "\033]7044;#7f4eb1\033\\";
