# Generated by hellwal

wallpaper='/mnt/data/appdata/motoko/wallpapers/Catppuccin Mocha/08. Catppuccin Mocha.png'

background='000001'
foreground='7f4eb1'
cursor='7f4eb1'
border='7f4eb1'

color0='000001'
color1='080890'
color2='4a0e8a'
color3='661a7e'
color4='3e1880'
color5='112e8f'
color6='1a397e'
color7='952eff'
color8='030307'
color9='0c0c2b'
color10='28153c'
color11='3c2044'
color12='32234c'
color13='202d57'
color14='24304c'
color15='7f4eb1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
