#!/bin/sh
# Needs the poinck/lampe for terminal app to work
# https://github.com/poinck/lampe

lampe -s 1 y
lampe -s 9 y
lampe -s 10 y
# Send both GUI and CLI notification to verify
# (Does not actually verify they have been turned on,
# simply verifies that commands are sent)
clear
echo "Philips Hue - Lights 1, 9 and 10 are on"
notify-send 'Philips Hue' 'Lights 1, 9 and 10 are on' -t 1500
