#!/bin/sh
# Needs the poinck/lampe for terminal app to work
# https://github.com/poinck/lampe
 
lampe -s 1 n
lampe -s 9 n
lampe -s 10 n

# Send both GUI and CLI notification to verify 
# (Does not verify the lights are actaully on, 
# simply verifys that the commands are sent)
clear
echo "Philips Hue - Lights 1, 9 and 10 are off"
notify-send 'Philips Hue' 'Lights 1, 9 and 10 are now off' -t 1500
