# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$cachylgreen = rgba(7dcfffff)
$cachymgreen = rgba(9ece6aff)
$cachydgreen = rgba(2ac3deff)
$cachylblue = rgba(7aa2f7ff)
$cachymblue = rgba(3d59a1ff)
$cachydblue = rgba(1a1b26ff)
$cachywhite = rgba(c0caf5ff)
$cachygrey = rgba(565f89ff)
$cachygray = rgba(9aa5ceff)
