# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = nautilus
$browser = librewolf
$applauncher = wofi --icons --matching fuzzy --monitor DP-4 --show drun 
$runlauncher = wofi --matching fuzzy --show run 
$emojilauncher = rofi -show emoji -m DP-4
$shutdownmenu = hyprexit.sh
$terminal = ghostty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$capturing = grim -g "$(slurp)" - | swappy -f -
