# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/
$MAIN = DP-1
$VERT = DP-5

monitor = DP-1, preferred, 1440x720, 1
monitor = DP-5, 2540x1440@59.94, 0x0, 1, transform, 3 


# If you need to scale things like steam etc, please uncomment these lines.
# Adjust GDK_SCALE accordingly to your liking.
#xwayland {
#  force_zero_scaling = true       # Unscale XWayland
#}

#env = GDK_SCALE, 1.25                   # GDK Scaling Factor
