[hades2]
save="/home/mr/Games/Heroic/Prefixes/default/Hades II/drive_c/users/steamuser/Saved Games/Hades II"

[hades]
save="/home/mr/Games/Heroic/Prefixes/default/Hades/drive_c/users/steamuser/Saved Games/Hades"
