#!/usr/bin/env bash

REPO=$(basename "$(git rev-parse --show-toplevel)")
MSG=$(git log -1 --pretty=%s)

NOTE="$HOME/.brain/diary/$(date +%Y/%m/%Y-%m-%d).md"

mkdir -p "$(dirname "$NOTE")"

echo ""
echo "### $(date +%H:%M):  " >> "$NOTE"
echo "Commit: ($REPO) $MSG" >> "$NOTE"
