#!/usr/bin/env bash

REPO=$(basename "$(git rev-parse --show-toplevel)")
MSG=$(git log -1 --pretty=%B)

NOTE="$HOME/.brain/diary/$(date +%Y/%m/%Y-%m-%d).md"

mkdir -p "$(dirname "$NOTE")"

echo ""
echo "### $(date +%H:%M) "$REPO":  " >> "$NOTE"
echo "\$ git commit -m \"$MSG\"" >> "$NOTE"
